language: node_js
node_js: '8'

cache:
  yarn: true

install:
  - yarn --frozen-lockfile --non-interactive

stages:
  - name: test
    if: (tag IS blank) OR (type != push) OR (repo != vuetifyjs/vuetify)
  - name: deploy
    if: (tag IS present) AND (type = push) AND (repo = vuetifyjs/vuetify)

jobs:
  include:
    - stage: test
      before_script:
        - yarn global add codecov
      script:
        - yarn run lint
        - lerna run test:coverage -- -i
      after_script:
        - codecov

    - stage: test
      script: yarn run build

    # Vuetify Github
    - stage: deploy
      before_script:
        - yarn global add codecov
      script:
        - cd packages/vuetify
        - yarn run lint
        - yarn run test:coverage -i && codecov
        - yarn run build
        - rm -rf release
        - mkdir -p release
        - for file in ./dist/*; do cp "$file" "${file/dist\/vuetify/release/vuetify-${TRAVIS_TAG}}"; done
        - zip -jr "release/vuetify-${TRAVIS_TAG}.zip" release/*
      deploy:
        - provider: script
          script: bash scripts/deploy.sh
          skip_cleanup: true
          on:
            repo: vuetifyjs/vuetify
            tags: true
        - provider: releases
          api_key: $GITHUB_API_KEY
          file: "release/vuetify-${TRAVIS_TAG}.zip"
          skip_cleanup: true
          on:
            repo: vuetifyjs/vuetify
            tags: true
